=== dhui333704github/cdb-router/src/main/resources/router-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:jms="http://www.expd.com/xsd/jms/cdb"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.expd.com/xsd/jms/cdb"
           elementFormDefault="qualified">
    <xs:element xmlns:cdb="http://www.expd.com/xsd/jms/cdb"
                name="router-configurations"
                type="cdb:RouterConfigurationsType"/>
    <xs:complexType name="JMSEnvironmentType">
        <xs:sequence>
            <xs:element xmlns:cdb="http://www.expd.com/xsd/jms/cdb" type="cdb:JMSProviderType"
                        name="jms-provider"/>
            <xs:element name="backup-jms-provider"
                        type="jms:JMSProviderType" maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="email-contact" maxOccurs="unbounded"
                        minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value=".+\@.+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="jms:JMSDomainType" name="domain"
                      use="required"/>
    </xs:complexType>
    <xs:complexType name="RouterConfigurationsType">
        <xs:sequence>
            <xs:element xmlns:cdb="http://www.expd.com/xsd/jms/cdb" type="cdb:JMSEnvironmentType"
                        name="environment" maxOccurs="unbounded"
                        minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="JMSDomainType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INT"/>
            <xs:enumeration value="DEV"/>
            <xs:enumeration value="QA"/>
            <xs:enumeration value="PROD"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="JMSProviderType">
        <xs:sequence>
            <xs:element name="messagingProviderHostName"
                        type="xs:token">
            </xs:element>
            <xs:element name="messagingProviderPortNumber">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:pattern value="\d+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:token" name="userName" maxOccurs="1" minOccurs="0"/>
            <xs:element type="xs:token" name="password" maxOccurs="1" minOccurs="0"/>
            <xs:element name="brokerNode" type="xs:token" maxOccurs="1" minOccurs="0"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== dhui333704github/cdb-router/src/main/resources/router-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<router-configurations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xmlns="http://www.expd.com/xsd/jms/cdb"
                       xsi:schemaLocation="http://www.expd.com/xsd/jms/cdb router-configuration.xsd">
    <environment domain="INT">
        <jms-provider>
            <messagingProviderHostName>localhost</messagingProviderHostName>
            <messagingProviderPortNumber>2507</messagingProviderPortNumber>
            <userName>app_cdb_router</userName>
            <password>app_cdb_router</password>
            <brokerNode>CHQ-PATRICKP-XP</brokerNode>
        </jms-provider>
        <backup-jms-provider>
            <messagingProviderHostName>localhost</messagingProviderHostName>
            <messagingProviderPortNumber>7777</messagingProviderPortNumber>
        </backup-jms-provider>
        <email-contact>patrick.podenski@expeditors.com</email-contact>
    </environment>
    <environment domain="DEV">
        <jms-provider>
            <messagingProviderHostName>msgd-chq.chq.ei</messagingProviderHostName>
            <messagingProviderPortNumber>8176</messagingProviderPortNumber>
            <userName>app_cdb_router</userName>
            <password>app_cdb_router</password>
            <brokerNode>dev2_CHQ1_node</brokerNode>
        </jms-provider>
        <email-contact>patrick.podenski@expeditors.com</email-contact>
        <email-contact>damion.provitola@expeditors.com</email-contact>
    </environment>
    <environment domain="QA">
        <jms-provider>
            <messagingProviderHostName>mgqai-chq.chq.ei</messagingProviderHostName>
            <messagingProviderPortNumber>28600</messagingProviderPortNumber>
            <userName>app_cdb_router</userName>
            <password>app_cdb_router</password>
            <brokerNode>qai_CHQ1_node</brokerNode>
        </jms-provider>
        <backup-jms-provider>
            <messagingProviderHostName>mgqai-chq-bu.chq.ei</messagingProviderHostName>
            <messagingProviderPortNumber>28600</messagingProviderPortNumber>
        </backup-jms-provider>
        <email-contact>vizdf.errors@expeditors.com</email-contact>
        <email-contact>test.administrator@expeditors.com</email-contact>
    </environment>
    <environment domain="PROD">
        <jms-provider>
            <messagingProviderHostName>msg.chq.ei</messagingProviderHostName>
            <messagingProviderPortNumber>8198</messagingProviderPortNumber>
            <userName>app_cdb_router</userName>
            <password>app_cdb_router</password>
            <brokerNode>pd2_CHQ1_node</brokerNode>
        </jms-provider>
        <backup-jms-provider>
            <messagingProviderHostName>msg-bu.chq.ei</messagingProviderHostName>
            <messagingProviderPortNumber>8198</messagingProviderPortNumber>
        </backup-jms-provider>
        <email-contact>damion.provitola@expeditors.com</email-contact>
    </environment>
</router-configurations>

=== dhui333704github/cdb-router/src/main/build/DEV/resources/router-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<router-configurations xmlns="http://www.expd.com/xsd/jms/cdb"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.expd.com/xsd/jms/cdb router-configuration.xsd">
	<environment  domain="INT">
		<jms-provider>
			<messagingProviderHostName>patp-ws.chq.ei</messagingProviderHostName>
			<messagingProviderPortNumber>2507</messagingProviderPortNumber>
			<userName>app_cdb_router</userName>
			<password>app_cdb_router</password>
			<brokerNode>CHQ-PATRICKP-XP</brokerNode>
		</jms-provider>
		<email-contact>patrick.podenski@expeditors.com</email-contact>
	</environment>
	<environment domain="DEV">
		<jms-provider>
			<messagingProviderHostName>msgd-chq.chq.ei</messagingProviderHostName>
			<messagingProviderPortNumber>8176</messagingProviderPortNumber>
			<userName>app_cdb_router</userName>
			<password>app_cdb_router</password>
			<brokerNode>dev2_CHQ1_node</brokerNode>
		</jms-provider>
		<email-contact>damion.provitola@expeditors.com</email-contact>
	</environment>
	<environment domain="QA">
		<jms-provider>
			<messagingProviderHostName>mgqai-chq.chq.ei</messagingProviderHostName>
			<messagingProviderPortNumber>28600</messagingProviderPortNumber>
			<userName>app_cdb_router</userName>
			<password>app_cdb_router</password>
			<brokerNode>qai_CHQ1_node</brokerNode>
		</jms-provider>
		<email-contact>joe.kauzlarich@expeditors.com</email-contact>
	</environment>
	<environment domain="PROD">
		<jms-provider>
			<messagingProviderHostName>msg.chq.ei</messagingProviderHostName>
			<messagingProviderPortNumber>8198</messagingProviderPortNumber>
			<userName>app_cdb_router</userName>
			<password>app_cdb_router</password>
			<brokerNode>pd2_CHQ1_node</brokerNode>
		</jms-provider>
		<email-contact>joe.kauzlarich@expeditors.com</email-contact>
		<email-contact>corey.phillips@expeditors.com</email-contact>
		<email-contact>tom.kao@expeditors.com</email-contact>
	</environment>
</router-configurations>

=== dhui333704github/cdb-router/src/main/build/DEV/router-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<router-configurations xmlns="http://www.expd.com/xsd/jms/cdb"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.expd.com/xsd/jms/cdb router-configuration.xsd">
	<environment domain="QA">
		<jms-provider>
			<messagingProviderHostName>mgqai-chq.chq.ei</messagingProviderHostName>
			<messagingProviderPortNumber>28600</messagingProviderPortNumber>
			<userName>app_cdb_router</userName>
			<password>app_cdb_router</password>
			<brokerNode>qai_CHQ1_node</brokerNode>
		</jms-provider>
		<backup-jms-provider>
			<messagingProviderHostName>mgqai-chq-bu.chq.ei</messagingProviderHostName>
			<messagingProviderPortNumber>28600</messagingProviderPortNumber>
		</backup-jms-provider>
		<email-contact>vizdf.errors@expeditors.com</email-contact>
		<email-contact>test.administrator@expeditors.com</email-contact>
	</environment>
</router-configurations>
